### ISSUE TITLE
Tester application

### ISSUE THREAD

**Issue by max12mx13** [dulvui/futsal-manager#5]
Hello, I saw you were looking for testers and I would be excited to try the app out!
My phone is a moto g7 play running lineage os 20 - android version 13 - and it is rooted.
Thanks, Max.

**Comment by dulvui** [comment]
Hello Max, thank you for being interested in my game!
Wow, I actually didn't expect someone actually wanting to test my game :joy: 
Do you have the Google Play Store installed on your phone? If yes you can simply write me an email to info@simondalvai.com with the email account you are signed in at the Google Play Store.
Otherwise I can send you the apk trough email and then this weekend I will try to set up a Github Action that uploads the apk to Github, so you can download it from there without the need of Googles services.

**Comment by dulvui** [comment]
You should have access now. If not, please reopen the issue or write me a email.

**Comment by max12mx13** [comment]
I don't seem to be able to access it, would it be ok for you to email me an apk. 
Sorry for any inconvenience caused

**Comment by dulvui** [comment]
No worries :)
I will extend the current Github action so that uploads the apk also to Github.
So you can download the apk from the releases section.
I'll let you know when it's avaiable.

**Comment by dulvui** [comment]
I created now a release on Github:
https://github.com/dulvui/futsal-manager/releases/
